### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by xiaozaoba** [NickleHuang/Deep-Understanding-Of-Java-High-Concurrency-Programming-Corrigendum#1]
# P84
![image](https://user-images.githubusercontent.com/58067537/143512415-51f55266-5a73-4124-9f38-082ff5886f8b.png)
文中写的第六位，应该是第七位

# P100
![image](https://user-images.githubusercontent.com/58067537/143512481-e691ef04-c3e7-41dd-a573-38c0fa7f7e9d.png)
文中写着req顺序锁，应该是seq顺序锁

**Comment by NickleHuang** [comment]
非常感谢，这确实是一个问题
